# Generated by Django 5.1.2 on 2024-12-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
