# Generated by Django 5.1.2 on 2024-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_muscialdescription_musical_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscialdescription',
            name='musical_image',
            field=models.ImageField(upload_to='games_images/'),
        ),
    ]
