# Generated by Django 5.1.2 on 2024-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_muscialdescription_musical_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bingo_name', models.CharField(max_length=255)),
                ('bingo_description', models.TextField()),
                ('bingo_image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='FindImposterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findimposter_name', models.CharField(max_length=255)),
                ('findimposter_description', models.TextField()),
                ('findimposter_image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='MonkeyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monkey_name', models.CharField(max_length=255)),
                ('monkey_description', models.TextField()),
                ('monkey_image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='PinataDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinata_name', models.CharField(max_length=255)),
                ('pinata_description', models.TextField()),
                ('pinata_image', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='SpinnerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spinner_name', models.CharField(max_length=255)),
                ('spinner_description', models.TextField()),
                ('spinner_image', models.ImageField(upload_to='games_images')),
            ],
        ),
    ]
